// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljtalwwhiekokkncitar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqdGFsd3doaWVrb2trbmNpdGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTIyMzksImV4cCI6MjA3MDQyODIzOX0.vYC-2EiIN2ClauYFpz-NIVJuEbD8fWIklvGFcJgfZ0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});